ZZinBros/miniprojects-2019

- .gitignore
- build.gradle
- src/main/java/com/woowacourse/zzinbros/post/domain/Post.java
- src/main/java/com/woowacourse/zzinbros/post/domain/PostException.java
- src/main/java/com/woowacourse/zzinbros/post/domain/UnAuthorizedException.java
- src/main/java/com/woowacourse/zzinbros/post/domain/User.java
- src/main/java/com/woowacourse/zzinbros/post/domain/repository/PostRepository.java
- src/main/java/com/woowacourse/zzinbros/post/dto/PostDataAssembler.java
- src/main/java/com/woowacourse/zzinbros/post/dto/PostRequestDto.java
- src/main/java/com/woowacourse/zzinbros/post/dto/PostResponseDto.java
- src/main/java/com/woowacourse/zzinbros/post/dto/UserResponseDto.java
- src/main/java/com/woowacourse/zzinbros/post/service/PostNotFoundException.java
- src/main/java/com/woowacourse/zzinbros/post/service/PostService.java
- src/test/java/com/woowacourse/zzinbros/ZzinbrosApplicationTests.java
- src/test/java/com/woowacourse/zzinbros/post/domain/PostTest.java
- src/test/java/com/woowacourse/zzinbros/resources/application.yml
> [안돌, 던] 게시글 구현

- src/main/java/com/woowacourse/zzinbros/user/domain/UserRepository.java
- src/main/java/com/woowacourse/zzinbros/user/dto/UserRequestDto.java
- src/main/java/com/woowacourse/zzinbros/user/exception/UserDuplicatedException.java
- src/main/java/com/woowacourse/zzinbros/user/service/UserService.java
- src/main/java/com/woowacourse/zzinbros/user/web/LoginController.java
- src/main/java/com/woowacourse/zzinbros/user/web/UserController.java
- src/test/java/com/woowacourse/zzinbros/user/domain/UserTest.java
- src/test/java/com/woowacourse/zzinbros/user/service/UserServiceTest.java
- src/test/java/com/woowacourse/zzinbros/user/web/UserControllerTest.java
1. refactor(package) : 테스트 패키지 분리
- user 패키지 안에 service, domain으로 패키지 분리
2. feat(controller) : UserController CRUD 구현
- 테스트는 MockMvc로 수행
- 권한 검사, 예외 처리 X
- ResponseEntity를 반환
- 페이지 이동 구현 X
3. refactor(controller) : User가 존재하지 않을 때 404에러 코드 반환
- 사용자 정보를 변경, 조회할 때 사용자가 존재하지 않을 경우 404에러코드 반환
- 테스트 추가
- MockMvc 때문에 UserRequestDto에 equals() 구현 (삭제 고려)
4. refacotr(controller, service) : 이메일이 중복될 때 예외 처리 
- Service는 UserDuplicatedException 발생
- Controller는 Accepted 응답 코드 반환
> [유저 관련 기능] UserController 클래스 구현

- src/main/java/com/woowacourse/zzinbros/demo/DemoController.java
- src/main/java/com/woowacourse/zzinbros/post/service/PostService.java
- src/main/java/com/woowacourse/zzinbros/post/web/PostController.java
- src/main/resources/application.yml
- src/main/resources/data.sql
- src/main/resources/templates/common/cards.html
- src/main/resources/templates/common/center-container.html
- src/main/resources/templates/element/card-contents.html
- src/main/resources/templates/element/card-header.html
- src/main/resources/templates/element/social-feed.html
- src/main/resources/templates/index.html
- src/test/java/com/woowacourse/zzinbros/post/domain/PostTest.java
- src/test/java/com/woowacourse/zzinbros/post/service/PostServiceTest.java
- 뷰에서 게시글 작성, 삭제, 조회 기능 추가
- 초기 데이터 추가
- 실패하는 게시글 도메인 테스트 해결
> feat(post): 뷰에서 게시글 작성, 삭제, 조회 기능 구현

- src/main/java/com/woowacourse/zzinbros/post/service/PostService.java
- src/main/java/com/woowacourse/zzinbros/post/web/PostController.java
- src/main/java/com/woowacourse/zzinbros/post/web/PostEditController.java
- src/main/resources/templates/common/header.html
- src/main/resources/templates/element/card-header.html
- src/main/resources/templates/element/social-feed.html
- src/main/resources/templates/post-modify.html
1. 게시글 수정 페이지 템플릿 추가
2. 게시글 수정 페이지 컨트롤러 추가
> [게시글] 뷰에서 게시글 수정기능 추가

- src/main/java/com/woowacourse/zzinbros/post/config/PostControllerExceptionAdvice.java
- src/main/java/com/woowacourse/zzinbros/post/domain/Post.java
- src/main/java/com/woowacourse/zzinbros/post/service/PostService.java
- src/main/java/com/woowacourse/zzinbros/post/web/PostController.java
- src/main/java/com/woowacourse/zzinbros/post/web/PostEditController.java
- src/test/java/com/woowacourse/zzinbros/post/domain/PostTest.java
- src/test/java/com/woowacourse/zzinbros/post/service/PostServiceTest.java
- 로그인 상태에서만 게시글 작성, 수정, 삭제
- 수정, 삭제 권한이 없을 경우 메인화면으로 redirect
> [게시글] 로그인 상태에 따라 게시글 작성, 수정, 삭제하도록 수정

- src/main/resources/templates/index.html
- src/main/resources/templates/layout/cards.html
- src/main/resources/templates/layout/center-container.html
- src/main/resources/templates/layout/headline.html
- src/main/resources/templates/login.html
- src/main/resources/templates/mypage-edit.html
- src/main/resources/templates/post-modify.html
- src/main/resources/templates/signup.html
> fix(templates): thymeleaf 경로 수정

- src/test/java/com/woowacourse/zzinbros/post/web/PostPageControllerTest.java
> Hotfix : 실패 테스트를 통과시켰습니다.

- src/main/resources/static/css/user-page.css
- src/main/resources/templates/common/header.html
- src/main/resources/templates/element/user-info-card.html
- src/main/resources/templates/layout/user-page-cover.html
- src/main/resources/templates/layout/user-page-info.html
- src/main/resources/templates/layout/user-page-tabs.html
- src/main/resources/templates/user-page.html
> 유저 페이지 메인 화면 추가

- src/main/java/com/woowacourse/zzinbros/user/domain/User.java
- src/main/resources/application.yml
안돌의 comment를 반영해서 innoDB로 변경했습니다
> setting(yml): databse-platform 설정 Mysql5Dialet -> MySQL5InnoDBDialect

- src/main/resources/application.yml
배포 서버에서 사용할 로그 설정을 변경하고, 서버에서는 필요 없을 devtools 관련 설정을 삭제했습니다.
> chore(logging): 로그 설정 변경

- src/main/java/com/woowacourse/zzinbros/comment/controller/CommentController.java
- src/main/java/com/woowacourse/zzinbros/comment/domain/Comment.java
- src/main/java/com/woowacourse/zzinbros/comment/domain/repository/CommentRepository.java
- src/main/java/com/woowacourse/zzinbros/comment/dto/CommentRequestDto.java
- src/main/java/com/woowacourse/zzinbros/comment/exception/CommentNotFoundException.java
- src/main/java/com/woowacourse/zzinbros/comment/exception/UnauthorizedException.java
- src/main/java/com/woowacourse/zzinbros/comment/service/CommentService.java
- src/test/java/com/woowacourse/zzinbros/comment/controller/CommentControllerTest.java
- src/test/java/com/woowacourse/zzinbros/comment/service/CommentServiceTest.java
며칠 전 코드 기반이라 지금의 코드와는 맞지 않는 부분들이 좀 있는데,
merge된 이후 수정할 예정.
> feat(Comment): 코멘트 기능 관련 백엔드 코드 추가

- src/main/java/com/woowacourse/zzinbros/comment/controller/CommentController.java
- src/main/java/com/woowacourse/zzinbros/comment/domain/Comment.java
- src/main/java/com/woowacourse/zzinbros/comment/service/CommentService.java
- src/test/java/com/woowacourse/zzinbros/comment/controller/CommentControllerTest.java
- src/test/java/com/woowacourse/zzinbros/comment/domain/CommentTest.java
- src/test/java/com/woowacourse/zzinbros/comment/service/CommentServiceTest.java
아침 데일리 미팅 시간에 했던 팀내 피드백에서 이야기 나왔던 사항들을 반영하였습니다.
> refactor(Comment): 아침의 팀내 피드백 반영

- src/main/resources/logback-access.xml
IDE에서 자동 리포맷을 하는 바람에 의도하지 않은 줄바꿈이 로그 출력에 들어가는 문제를 해결하였습니다.
> fix(logback-access.xml): 의도하지 않은 줄바꿈 삽입 제거

- src/test/java/com/woowacourse/zzinbros/mediafile/web/support/AuthedWebTestClient.java
- src/test/java/com/woowacourse/zzinbros/post/web/PostWithImageControllerTest.java
> fix(test): S3 reponseTimeout 변경

- src/main/resources/static/js/fetch-api.js
- src/main/resources/static/js/friend-add.js
- src/main/resources/static/js/mypage-edit.js
- src/main/resources/static/js/post-edit.js
- src/main/resources/static/js/post-like.js
- src/main/resources/static/js/social-feed.js
- src/main/resources/static/js/user-page-add.js
- AjaxApi 인스턴스를 전역으로 변경
- AjaxApi 내부 bodyData를 오브젝트 리터럴로 변경
> refactor(js): 피드백 반영

- src/main/java/com/woowacourse/zzinbros/post/domain/Post.java
- src/main/java/com/woowacourse/zzinbros/post/domain/PostLike.java
- src/main/java/com/woowacourse/zzinbros/post/service/PostService.java
- src/test/java/com/woowacourse/zzinbros/post/domain/PostTest.java
- src/test/java/com/woowacourse/zzinbros/post/service/PostServiceTest.java
Post와 PostLike를 양방향에서 단방향으로 수정
> 좋아요 기능 리팩토링

- src/test/java/com/woowacourse/zzinbros/demo/DemoControllerTest.java
> test(DemoController): 추가

- .gitignore
- src/main/java/com/woowacourse/zzinbros/comment/controller/CommentController.java
- src/main/java/com/woowacourse/zzinbros/comment/controller/CommentControllerExceptionAdvice.java
- src/main/java/com/woowacourse/zzinbros/comment/dto/CommentResponseDto.java
- src/main/java/com/woowacourse/zzinbros/comment/exception/CommentNotFoundException.java
- src/main/java/com/woowacourse/zzinbros/comment/exception/UnauthorizedException.java
- src/main/java/com/woowacourse/zzinbros/comment/service/CommentService.java
- src/main/java/com/woowacourse/zzinbros/user/web/support/UserSession.java
- src/main/resources/application-local.yml
- src/main/resources/application-test.yml
- src/main/resources/static/css/app.css
- src/main/resources/static/js/comment.js
- src/main/resources/templates/element/card-action-detail.html
- src/main/resources/templates/element/cards.html
- src/main/resources/templates/index.html
- src/main/resources/templates/user-page.html
- src/test/java/com/woowacourse/zzinbros/comment/controller/CommentControllerTest.java
- src/test/java/com/woowacourse/zzinbros/comment/domain/CommentTest.java
- src/test/java/com/woowacourse/zzinbros/comment/service/CommentServiceTest.java
오늘 러너덕님과 작업한 코멘트 쪽 코드입니다.
* 예외 발생시 이를 잡는 Controller Advice 작성
* 각 예외별로 다른 HTTP Status Code 적용
* `CommentResponseDto` 객체를 서버측 응답에 적용
* 댓글 작업 실패시에 대한 테스트 작성
* 테스트 프로필에서 좀 더 자세한 로그 출력
> refactor(Comment): 오류 처리 및 테스트 개선

- src/main/java/com/woowacourse/zzinbros/comment/controller/CommentControllerExceptionAdvice.java
- src/main/java/com/woowacourse/zzinbros/post/web/PostPageController.java
- src/main/java/com/woowacourse/zzinbros/user/domain/Friend.java
- src/main/java/com/woowacourse/zzinbros/user/domain/FriendRequest.java
- src/main/java/com/woowacourse/zzinbros/user/domain/User.java
- src/main/java/com/woowacourse/zzinbros/user/domain/repository/FriendRepository.java
- src/main/java/com/woowacourse/zzinbros/user/domain/repository/FriendRequestRepository.java
- src/main/java/com/woowacourse/zzinbros/user/service/FriendService.java
- src/main/java/com/woowacourse/zzinbros/user/web/controller/FriendController.java
- src/main/resources/application-local.yml
- src/main/resources/templates/element/userpage/user-page-cover.html
- src/test/java/com/woowacourse/zzinbros/post/domain/repository/PostRepositoryTest.java
- src/test/java/com/woowacourse/zzinbros/post/web/PostPageControllerTest.java
- src/test/java/com/woowacourse/zzinbros/user/domain/UserBaseTest.java
- src/test/java/com/woowacourse/zzinbros/user/domain/UserTest.java
- src/test/java/com/woowacourse/zzinbros/user/domain/repository/FriendRepositoryTest.java
- src/test/java/com/woowacourse/zzinbros/user/domain/repository/FriendRequestRepositoryTest.java
- src/test/java/com/woowacourse/zzinbros/user/domain/repository/UserAndFriendRepositoryTest.java
- src/test/java/com/woowacourse/zzinbros/user/service/FriendServiceTest.java
- src/test/java/com/woowacourse/zzinbros/user/web/controller/FriendControllerTest.java
- Friend, FriendRequest 분리
- FriendService 수정
- 기존 Mock테스트 삭제
- 프론트 코드 변경
> refactor(friend): 친구 관계 재설정

- src/main/java/com/woowacourse/zzinbros/demo/DemoController.java
- src/test/java/com/woowacourse/zzinbros/demo/DemoControllerTest.java
1. 로그아웃 상태에서 index 페이지에 접속할 때 entrance 페이지로 리다이렉트
> entrance, index 페이지 제어 방식 변경

- src/main/resources/static/css/entrance.css
- src/main/resources/templates/entrance.html
- src/main/resources/templates/layout/entrance/headline.html
- src/main/resources/templates/layout/entrance/left-logo.html
- src/main/resources/templates/layout/entrance/login-area.html
css로 최대 너비 설정을 하고, entrance.css 파일로 entrance 관련 css들을 관리하도록
수정하였습니다.
> entrance 페이지 logo max-width 설정

- src/main/java/com/woowacourse/zzinbros/common/config/upload/FileUploadExceptionAdvice.java
- src/main/resources/application.yml
- src/main/resources/static/js/social-feed.js
- js에서 파일 크기 체크
- ExceptionHandler 추가
> fix(multipartfile): 파일 크기 초과 핸들러 추가

- src/main/java/com/woowacourse/zzinbros/comment/dto/CommentResponseDto.java
- src/main/java/com/woowacourse/zzinbros/comment/web/controller/rest/CommentController.java
- src/main/java/com/woowacourse/zzinbros/common/domain/BaseEntity.java
- src/main/java/com/woowacourse/zzinbros/common/web/controller/rest/DateTimeController.java
- src/main/java/com/woowacourse/zzinbros/post/domain/Post.java
- src/test/java/com/woowacourse/zzinbros/common/domain/TestBaseMock.java
- src/test/java/com/woowacourse/zzinbros/post/service/PostServiceTest.java
ZonedDateTime은 RestController가 아닌 경우(Post 등) 문제가 있어서, 차선책으로 OffsetDateTime을 적용하였습니다. 어차피 DB에서는 TimeZone 정보가 저장이 안 되더라고요.
> refactor(OffsetDateTime): LocalDateTime을 OffsetDateTime으로 교체
